export const COLORS = {
brown: 'color: brown',
red: 'color: red',
green: 'color: green',
blue: 'color: blue',
yellow: 'color: yellow',
purple: 'color: purple',
cyan: 'color: cyan',
white: 'color: white',
black: 'color: black',
gray: 'color: gray',
orange: 'color: orange',
pink: 'color: pink',
violet: 'color: violet',

// 💖 Rosados
    babyPink: 'color: #F8C8DC',
    blushPink: 'color: #F4C2C2',
    cottonCandy: 'color: #FFBCD9',
    bubblegumPink: 'color: #FFB7D5',
    pastelPink: 'color: #FFD1DC',
    fairyPink: 'color: #FADADD',
    princessPink: 'color: #F78FB3',
    sakuraPink: 'color: #FFB7C5',
    rosePink: 'color: #FF66B2',
    strawberryMilk: 'color: #F4A6B8',
    cherryBlossom: 'color: #F8D7E3',
    barbiePink: 'color: #E0218A',

  // 💜 Morados y lilas
    lavender: 'color: #E6E6FA',
    lilac: 'color: #C8A2C8',
    pastelPurple: 'color: #D8BFD8',
    softViolet: 'color: #DDA0DD',
    orchid: 'color: #DA70D6',
    wisteria: 'color: #C9A0DC',
    periwinkle: 'color: #CCCCFF',
    unicornPurple: 'color: #B57EDC',
    dreamyLilac: 'color: #DCD0FF',

  // 💙 Azules pastel
    babyBlue: 'color: #89CFF0',
    skyBlue: 'color: #87CEEB',
    powderBlue: 'color: #B0E0E6',
    iceBlue: 'color: #D6F0FF',
    cloudBlue: 'color: #CFEFFF',
    pastelBlue: 'color: #AEC6CF',
    dreamyBlue: 'color: #B7D9F7',
    periwinkleBlue: 'color: #C3CDE6',

 // 🌈 pastel 
    pastelMint: 'color: #AAF0D1',
    mintCream: 'color: #F5FFFA',
    butterYellow: 'color: #FFF1B5',
    peachCream: 'color: #FFE5B4',
    vanillaCream: 'color: #FFF8DC',
    roseGold: 'color: #B76E79',
    champagnePink: 'color: #F7E7CE',
    moonGlow: 'color: #FDFD96',
};